angular.module('ccspApp', [
	'ngRoute',
  'ngAnimate',
	'core',
	'applicationDetail',
	'applicationList',
	'applicationListAll',
  'employeeDetail',
  'employeeDetailEdit',
  'spouseDetail',
  'spouseDetailEdit',
  'appointmentDetail',
  'childrenList',
  'childrenListEdit',
  'incomeDetail',
  'incomeDetailEdit',
  'awardDetail',
  'awardDetailEdit',
  'financialDocumentsDetail',
  'financialDocumentsEdit',
  'datatables',
  'ui.bootstrap',
  // 'angularMoment'
]);
