angular.module('ccspApp', [
	'ngRoute',
  'ngAnimate',
	'core',
	'applicationDetail',
	'applicationList',
  'employeeDetail',
  'employeeDetailEdit',
  'spouseDetail',
  'spouseDetailEdit',
  'childrenList',
  'incomeDetail',
  'awardDetail',
  'awardDetailEdit',
  'financialDocumentsDetail',
  'financialDocumentsEdit',
  'datatables',
  'ui.bootstrap'
]);
